### ISSUE TITLE
Cards don't appear on Firefox

### ISSUE THREAD

**Issue by timcoughlan** [IET-OU/our-journey#26]
Hi @nfreear,

I was just testing the changes I've made and thought I'd try it on Firefox rather than Chrome. It seems that the cards do not appear at all really. Not sure quite what is going on there but thought it was worth mentioning as I think the last time I looked it did work just about and perhaps this is something to look into in terms of general compatibility of the code.

Thanks,

Tim.

**Comment by nfreear** [comment]
Firefox fixes on 26 July, and in August by @nfreear and @timcoughlan.

Closing,

N.
